In [1]:
import matplotlib.pyplot as plt
import numpy


In [1]:
NO2_conc = [0,10,20,30,40,50,60,70,80,90,100,200,300,400,500,600,700,800,900] 
rs_ro = [0,3,4,5.5,8,11,15,19,25,30,35,150,350,800,1100,1900,2500,3500,4500]


In [2]:
import numpy.polynomial.polynomial as poly


In [5]:
poly.polyfit(numpy.log10(NO2_conc),numpy.log10(rs_ro),1)

array([-1.92055969,  1.82968412])

In [29]:
coefs = poly.polyfit(NO2_conc,rs_ro,7)

In [30]:
x_new=[]
for i in NO2_conc:
    x_new.append(i+0.5)

In [31]:
ffit = poly.polyval(x_new,coefs)

In [45]:
plt.plot(x_new,ffit)
plt.plot(NO2_conc, rs_ro, color='red')
plt.plot()

In [46]:
plt.show()


In [34]:
coefs


array([  2.09032045e+00,  -2.50294293e-02,   4.64041545e-03,
        -1.87428761e-05,   1.13387935e-07,  -2.53021577e-10,
         2.53336415e-13,  -9.44876820e-17])

In [44]:
rs_ro

[0,
 3,
 4,
 5.5,
 8,
 11,
 15,
 19,
 25,
 30,
 35,
 150,
 350,
 800,
 1100,
 1900,
 2500,
 3500,
 4500]

In [35]:
ffit


array([  2.07896350e+00,   2.31876631e+00,   3.38500756e+00,
         5.20353015e+00,   7.72157092e+00,   1.09051731e+01,
         1.47367665e+01,   1.92129112e+01,   2.43421986e+01,
         3.01433077e+01,   3.66432083e+01,   1.49032532e+02,
         3.75234843e+02,   7.31743545e+02,   1.20951403e+03,
         1.80721889e+03,   2.55618013e+03,   3.48935642e+03,
         4.50676384e+03])

In [47]:
test_equation =[]
for x in NO2_conc:
    test_equation.append((-9.44876820e-17*(x)**7) +(2.53336415e-13*(x)**6) -(2.53021577e-10 *(x)**5)+(1.13387935e-07 *(x)**4) -(1.87428761e-05*(x)**3) +(4.64041545e-03*(x)**2) -(2.50294293e-02*(x))+2.09032045)

In [48]:
test_equation


[2.09032045,
 2.2864336554838385,
 3.3133035283399273,
 5.09563224012983,
 7.579649816809221,
 10.730518011420314,
 14.52990229246556,
 18.97370718578346,
 24.069970207747343,
 29.836909627607838,
 36.3011212968,
 148.2159233804,
 373.7788593315999,
 729.6484755012001,
 1206.8380808,
 1803.892939154798,
 2551.9825138523956,
 3484.2859720436,
 4502.049157679183]

In [37]:
x = [2.53240, 1.91110, 1.18430, 0.95784, 0.33158,
     -0.19506, -0.82144, -1.64770, -1.87450, -2.2010]

y = [-2.50400, -1.62600, -1.17600, -0.87400, -0.64900,
     -0.477000, -0.33400, -0.20600, -0.10100, -0.00600]

coefficients = poly.polyfit(x, y, 6)

In [38]:
coefficients

array([-0.5139088 , -0.30660343, -0.17468383, -0.02020429,  0.03629611,
       -0.00160756, -0.00412906])

In [ ]:
rs/ro = 66875.5
ppb = between 10 and 45 (can be significantly more in homes)
assume for now it is 15



In [49]:
x =15
ans = (-9.44876820e-17*(x)**7) +(2.53336415e-13*(x)**6) -(2.53021577e-10 *(x)**5)+(1.13387935e-07 *(x)**4) -(1.87428761e-05*(x)**3) +(4.64041545e-03*(x)**2) -(2.50294293e-02*(x))+2.09032045

In [50]:
ans

2.7012662753778365

In [1]:
import sys
import Adafruit_DHT
import time
import csv
import datetime
import math
import numpy
from MCP_3008 import *

MCP_3008.py:44: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(SPIMOSI, GPIO.OUT)
MCP_3008.py:46: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(SPICLK, GPIO.OUT)
MCP_3008.py:47: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(SPICS, GPIO.OUT)


In [2]:
analogue_settings ={'co2':[0,5,1000000.,0],
					'lux':[1,3.3,0,22000.],
					}

In [24]:
read_pin =3.3

In [25]:
vout = read_pin/1023. *sett[1]
numpy.errstate(divide='ignore')
if vout not in [sett[1], 0.0]:
    if sett[2] !=0:
        result =(sett[2] *sett[1])/vout - sett[2]
    else:
        result = sett[3]/((sett[1]/vout)-1)

    print result
else:
    print 0

309000000.0


In [17]:
sett = analogue_settings['co2']

In [8]:
vout

0.0